### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by halfwit**
Allow development of wiki using docker for easier setup

### CODE REVIEW

**Review by itsrachelfish — CHANGES_REQUESTED** [review]
I followed the instructions in the readme, created the `.env` file and then `src/config.php` as well as `src/ban.php` but I got this error while running `sudo docker compose up -d`

```
Creating wiki-php   ... error

ERROR: for wiki-php  Cannot start service wiki: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/rachel/Projects/Wetfish/classic/wiki/config/config.php\\\" to rootfs \\\"/var/lib/docker/overlay2/4e3191a11c4a5f4206e90005f519fd6fb5ca8b86615c132778d1dd50576cf486/merged\\\" at \\\"/var/lib/docker/overlay2/4e3191a11c4a5f4206e90005f519fd6fb5ca8b86615c132778d1dd50576cf486/merged/var/www/src/config.php\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for wiki  Cannot start service wiki: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/rachel/Projects/Wetfish/classic/wiki/config/config.php\\\" to rootfs \\\"/var/lib/docker/overlay2/4e3191a11c4a5f4206e90005f519fd6fb5ca8b86615c132778d1dd50576cf486/merged\\\" at \\\"/var/lib/docker/overlay2/4e3191a11c4a5f4206e90005f519fd6fb5ca8b86615c132778d1dd50576cf486/merged/var/www/src/config.php\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

**Comment by halfwit** [comment]
There was also the issue with load.js, the hashed variant works correctly.

**Review by itsrachelfish — CHANGES_REQUESTED** [review]
docker-compose is working now, but npm install isn't.

```
rachel@pop-os:~/Projects/Wetfish/classic/wiki$ sudo docker-compose exec wiki npm install --prefix src
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/fishy
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/home/fishy'
npm ERR!  [OperationalError: EACCES: permission denied, mkdir '/home/fishy'] {
npm ERR!   cause: [Error: EACCES: permission denied, mkdir '/home/fishy'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'mkdir',
npm ERR!     path: '/home/fishy'
npm ERR!   },
npm ERR!   isOperational: true,
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/fishy'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/fishy
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/home/fishy'
npm ERR!  [OperationalError: EACCES: permission denied, mkdir '/home/fishy'] {
npm ERR!   cause: [Error: EACCES: permission denied, mkdir '/home/fishy'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'mkdir',
npm ERR!     path: '/home/fishy'
npm ERR!   },
npm ERR!   isOperational: true,
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/fishy'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

**Review by halfwit — COMMENTED** [review]
This all seems to work now

**Review by itsrachelfish — APPROVED** [review]
Yep, it's working now!

**Pull request merged**
